name: Rust SDK CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build and Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Install dependencies
        run: |
          rustup component add clippy rustfmt
      
      - name: Check code
        run: cargo check --all-targets
      
      - name: Run tests
        run: cargo test
      
      - name: Build binary
        run: cargo build --release
      
      - name: Format code
        run: cargo fmt --check
      
      - name: Lint code
        run: cargo clippy --all-targets -- -D warnings
